// FOR, SIRVE PARA REPETIR/ITERAR UN CODIGO, LA CANTIDAD
// DE VECES QUE LE INDIQUEMOS

// TENEMOS 3 SECCIONES,

// 1. LA INICIALIZACION DE UNA VARIABLE DE CONTROL,
// 2. UNA CONDICION RELACIONADA A ESA VARIABLE,
// 3. UN INCREMENTO DE LA VARIABLE DE CONTROL

for (let i = 1; i <= 10; i++) {
  // LOGICA DE UN CODIGO QUE EN ESTE CASO, QUIERO ITERAR 10 VECES
  console.log(i);
};
