// FOR, SIRVE PARA REPETIR/ITERAR UN CODIGO, LA CANTIDAD
// DE VECES QUE LE INDIQUEMOS

// TENEMOS 3 SECCIONES,

// LA INICIALIZACION DE UNA VARIABLE DE CONTROL,
// UNA CONDICION RELACIONADA A ESA VARIABLE,
// UN INCREMENTO DE LA VARIABLE DE CONTROL

for (let i = 1; i <= 10; i++) {
  // LOGICA DE UN CODIGO QUE EN ESTE CASO, QUIERO ITERAR 10 VECES
  console.log(i);
};
